name: 'Python Security'
author: 'Anthony Shaw'
description: 'Scan your Python Code for security issues'
inputs:
  path:
    description: 'Path to code to scan'
    required: true
    default: '.'
outputs:
  result:
    description: 'Results from the scan'
runs:
  using: 'docker'
  image: 'tonybaloney/pycharm-security/pycharm-security-action@1.4.2'
  args:
    - ${{ inputs.path }}
branding:
  icon: 'lock'
  color: 'blue'