name: 'PyCharm Python Security Scanner'
author: 'Anthony Shaw'
description: 'Scan your Python Code for security issues'
inputs:
  path:
    description: 'Path to code to scan'
    required: true
    default: '.'
outputs:
  result:
    description: 'Results from the scan'
runs:
  using: 'docker'
  image: '.github/actions/Dockerfile'
  args:
    - ${{ inputs.path }}
branding:
  icon: 'lock'
  color: 'blue'
