name: Build plugin for tags

on:
  release:
    types: [published, created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: test -PintellijPublishToken=FAKE_TOKEN -PideaPath="" --info
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: buildPlugin -PintellijPublishToken=FAKE_TOKEN -PideaPath="" --info

