name: Build plugin for tags

on:
  push:
    branches:
      - master
  release:
    types: [published, created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: test -PintellijPublishToken=FAKE_TOKEN -PideaPath="" --info
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: buildPlugin -PintellijPublishToken=FAKE_TOKEN -PideaPath="" --info
    - name: Upload build
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: "pycharm-security-${version}.zip"
        # Directory containing files to upload
        path: build/distributions
        env:
          version: $GITHUB_REF
