name: 'Testing Custom Action'
on: [push]

jobs:
  test_example:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v1
        repository: 'tonybaloney/pycharm-security-testing'
      - name: Run PyCharm Security
        id: pycharm-security
        uses: ./
        with:
          path: .