name: 'Testing Custom Action'
on: [push]

jobs:
  test_example:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v1
        with:
          repository: 'tonybaloney/pycharm-security-testing'
          ref: 'master'
          path: 'pycharm-security'
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@${{ github.event.pull_request.head.sha }}
        with:
          path: .